cmd/network.go

Add missing network policies for knative serving + kfserving

---

cmd/limitrange.go
cmd/quotas.go
cmd/rbac.go

This will resolve https://github.com/StatCan/aaw-kubeflow-profiles-controller/issues/3

feat(limits): Add default limit ranges for each kubeflow-profile

---

cmd/authpolicy.go
cmd/limitrange.go
cmd/minio.go
cmd/network.go
cmd/notebook.go
cmd/quotas.go
cmd/rbac.go
cmd/root.go

Issue: https://github.com/StatCan/aaw-kubeflow-profiles-controller/issues/17
Update .go files to use requeue time env variable; replacing hard coded value

feat(requeue): Add requeue time env variable

---

cmd/notebook.go

Closes https://github.com/StatCan/jupyter-apis/issues/104

feat(i18n):Add i18n for ProB desc

---

README.md
cmd/blob-csi.go
go.mod
go.sum

Closes https://github.com/StatCan/daaas/issues/1007

feat(blob-csi): add blob-csi driver PV and PVCs

---

cmd/notebook.go

Closes https://github.com/StatCan/daaas/issues/1011

feat(blob-csi-injector): add PodDefault for blob-csi

---

.vscode/launch.json
cmd/cloud-main.go

closes https://github.com/StatCan/daaas/issues/1147

feat(cloud-main.go): add cloud main controller

---

.vscode/launch.json
cmd/trino.go

closes #https://github.com/StatCan/daaas/issues/1298
Trino controller iterates through each profile, extracts kubeflow edit role-bindings. Controller compiles a rules (table and schema rule) for each profile and makes an update to 3 configmaps (catalogs: standard, premium and prob).

feat:trino rbac controller

---

cmd/network.go
cmd/s3proxy.go

s3proxy controller + network policy controller to allow per-namespace s3proxy/s3-explorer installation.
Closes [daaas#1037](https://github.com/StatCan/daaas/issues/1037)

@cbrown/1037 s3proxy controller

---

.vscode/launch.json
cmd/trino-schema.go

closes https://github.com/StatCan/daaas/issues/1319
The namespace trino-admin will have admin permissions on schemas and tables, only user authorized to create schemas for users. I've already created the trino-admin ns in kubeflow and updated  rules.json

feat(trino):create trino schema controller

---

cmd/cloud-main.go
cmd/network.go

Match new capability labels created by profile state controller. Addresses https://github.com/StatCan/daaas/issues/1335

@cbrown/1335 non employee rbac

---

cmd/network.go

Reverts https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/26/commits/2bca1dfe92f09febf46364c125f2845707de05d0
Closes StatCan/daaas-private#25

fix(protb): add https egress for prot-b notebooks

---

.github/workflows/publish.yml
cmd/rbac.go

Part of https://github.com/StatCan/daaas/issues/1449

Remove pipeline role-binding

---

.github/workflows/publish.yml
cmd/rbac.go

Reverts StatCan/aaw-kubeflow-profiles-controller#81

Revert "Remove pipeline role-binding"

---

cmd/trino-schema.go

Bring back trino schema controller. Modifying the X-trino-user

refactor: trino schema controller

---

cmd/trino-schema.go
cmd/trino.go

Refactored Trino controllers to work well with Oauth usernames as Trino usernames.

deploy: trino profiles & schema controller in Dev

---

cmd/trino-schema.go

Fix bug with trino: Create schema being stuck in finishing stage

Refactor trino schema controller

---

cmd/trino.go

refactor controller to use cloud/statcan email as schema and table owner

refactor(trino-controller): change owner name on schemas and tables

---

cmd/rbac.go

Part of removing pipelines for prod. 
https://github.com/StatCan/daaas/issues/1499

fix: remove role-binding pipeline

---

cmd/blob-csi.go

closes https://github.com/StatCan/daaas/issues/1496

feat(blob-csi): add subfolder mounting for fdi containers

---

cmd/blob-csi.go

Issue: https://github.com/StatCan/daaas/issues/1546

refactor(blob-csi.go): fdi aaw gateway

---

cmd/s3proxy.go

for https://github.com/StatCan/daaas/issues/1648

updated s3proxy virtual service

---

cmd/s3proxy.go

for https://github.com/StatCan/daaas/issues/1651

added s3proxy virtual service match

---

cmd/network.go

DO NOT MERGE
related to https://github.com/StatCan/daaas/issues/1328

chore(netpol): prepare update

---

cmd/notebook.go

Closes https://github.com/StatCan/aaw/issues/1789
Will need to verify on Dev if the protected B still blocks everything as expected.

Remove protected B from podDefault

---

.github/workflows/build.yml
.github/workflows/publish.yml

Related to https://github.com/StatCan/aaw-private/issues/112

chore(scanning): migrate from azure container scan to trivy

---

.github/workflows/build.yml
.github/workflows/publish.yml

~~still needs the variable added to the repo~~ variable has been added to the repo, just need to fix the CVE but thats a different task.

chore(allowlist): make secret

---

cmd/blob-csi.go

Allow method to proceed on error instead of failing with fatal

chore(blob-csi): Azblob auth error handling

---

cmd/notebook.go

Closes https://github.com/StatCan/aaw/issues/1848
Part 2/3

Remove configuration

---

cmd/secret.go

Related to https://jirab.statcan.ca/browse/BTIS-200

Add secret.go

---

.github/workflows/build.yml
.github/workflows/publish.yml
cmd/network.go

Jira: https://jirab.statcan.ca/browse/BTIS-432
Add network policies for all users for sql server and oracle.

Create SQL Server and Oracle network policies for database connectivity.

---

cmd/ontap-cvo.go

for https://jirab.statcan.ca/browse/BTIS-481

feat(netapp): Handle master filers list

---

cmd/ontap-cvo.go

for https://jirab.statcan.ca/browse/BTIS-482

feat(netapp): update function to check if S3 bucket exists

---

cmd/ontap-cvo.go

for https://jirab.statcan.ca/browse/BTIS-488

feat(netapp): added hashing function for bucketnames

---

cmd/ontap-cvo.go

for https://jirab.statcan.ca/browse/BTIS-483

feat(netapp): add function to create error configmap

---

cmd/ontap-cvo.go

see [BTIS-514](https://jirab.statcan.ca/browse/BTIS-514) for more information
[Goplay snippet](https://goplay.tools/snippet/kyT7lpbFJ0M)

chore(user groups): add api calls

---

cmd/ontap-cvo.go

for https://jirab.statcan.ca/browse/BTIS-492

feat(ontap): Update error configmap logic

---

cmd/ontap-cvo.go

bad branch name
[BTIS-517](https://jirab.statcan.ca/browse/BTIS-517)
[Snippet for duplication in requesting shares](https://goplay.tools/snippet/nQ0zoV5Fog6)

chore(shares): check for duplicates

---

cmd/ontap-cvo.go

The password for the sas filers is not the same as the one for the field filers.
[BTIS-522](https://jirab.statcan.ca/browse/BTIS-522?focusedId=3187239&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3187239)

chore(ontap): use new format for secret

---

cmd/ontap-cvo.go

To be compatible with k8s specification
[BTIS-522](https://jirab.statcan.ca/browse/BTIS-522?focusedId=3187376&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3187376)

chore(secret name format): convert _ to -

---

cmd/ontap-cvo.go

update logging as well as move around sas ip settings

chore(sas filer info): fix placement

---

cmd/kerberos.go

for https://jirab.statcan.ca/browse/BTIS-703 
To test, you need to create a secret in your namespace, named "kerberos-keytab". This controller doesn't read the secret, so really, anything can be in there for testing. But fora more real test, you can go in a notebook and run "ktutil-keytab" in a terminal, and then proceed through the steps. This will create the secret in your namespace.

feat(kerberos): Create controller for kerberos resources
